import { prisma } from "../../config/prisma.js";
import { oauth2Client, GOOGLE_SCOPES } from "../../config/google.js";
import { AppError } from "../../utils/api.js";
import { startOfDay } from "../../utils/dates.js";
import { google } from "googleapis";

/**
 * Generates the Google Authorization URL for user consent
 */
export function getGoogleAuthUrl() {
  return oauth2Client.generateAuthUrl({
    access_type: "offline", // Required to get Refresh Token
    scope: GOOGLE_SCOPES,
    include_granted_scopes: true,
    prompt: "consent", // Ensure we get the refresh token every time they link
  });
}

/**
 * Exchanges auth code for tokens and links user profile
 */
export async function linkGoogleAccount(userId: number, code: string) {
  const { tokens } = await oauth2Client.getToken(code);
  
  if (!tokens.refresh_token) {
    // If user already linked, Google might not send refresh token unless prompt=consent is used
    // or if we already have it.
    throw new AppError("Failed to obtain refresh token. Please un-link and re-link your account.", 400);
  }

  oauth2Client.setCredentials(tokens);

  const oauth2 = google.oauth2({ version: "v2", auth: oauth2Client });
  const userInfo = await oauth2.userinfo.get();

  if (!userInfo.data.id) {
    throw new AppError("Failed to fetch Google user profile.", 500);
  }

  // Update user in DB
  const updatedUser = await prisma.user.update({
    where: { id: userId },
    data: {
      googleId: userInfo.data.id,
      googleRefreshToken: tokens.refresh_token,
      isGoogleLinked: true,
    },
  });

  return {
    email: userInfo.data.email,
    isLinked: updatedUser.isGoogleLinked,
  };
}

/**
 * Unlinks Google account from user
 */
export async function unlinkGoogleAccount(userId: number) {
  await prisma.user.update({
    where: { id: userId },
    data: {
      googleId: null,
      googleRefreshToken: null,
      isGoogleLinked: false,
    },
  });

  return { isLinked: false };
}

/**
 * Creates a Google Meet link by creating a temporary calendar event
 */
export async function createMeetLink(userId: number, summary: string = "HRMS Instant Meeting") {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    throw new AppError("Google account not linked.", 403);
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });

  const event = await calendar.events.insert({
    calendarId: "primary",
    conferenceDataVersion: 1,
    requestBody: {
      summary,
      description: "Generated by HRMS Command Center",
      start: { dateTime: new Date().toISOString() },
      end: { dateTime: new Date(Date.now() + 3600000).toISOString() }, // 1 hour later
      conferenceData: {
        createRequest: {
          requestId: `hrms-meet-${Date.now()}`,
          conferenceSolutionKey: { type: "hangoutsMeet" },
        },
      },
    },
  });

  const meetLink = event.data.hangoutLink;

  if (!meetLink) {
    throw new AppError("Failed to generate Google Meet link.", 500);
  }

  return { meetLink };
}

/**
 * Syncs an approved leave request to the employee's Google Calendar as an OOO event
 */
export async function syncLeaveToGoogleCalendar(params: {
  employeeId: number;
  startDate: Date;
  endDate: Date;
  leaveTypeName: string;
  reason: string;
}) {
  const user = await prisma.user.findFirst({
    where: { employee: { id: params.employeeId } },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    // Silently return if not linked, or we could log it.
    // For now, we don't want to block the leave approval process if Google is not linked.
    return { synced: false, reason: "Google account not linked" };
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });

  try {
    await calendar.events.insert({
      calendarId: "primary",
      requestBody: {
        summary: `OOO: ${params.leaveTypeName}`,
        description: `Approved Leave from HRMS. Reason: ${params.reason}`,
        start: { date: params.startDate.toISOString().split("T")[0] },
        end: { date: new Date(params.endDate.getTime() + 86400000).toISOString().split("T")[0] }, // end date is exclusive in Google Calendar
        transparency: "opaque", // busy
        status: "confirmed",
      },
    });

    return { synced: true };
  } catch (error) {
    console.error("Failed to sync leave to Google Calendar:", error);
    return { synced: false, error };
  }
}

/**
 * Syncs all future holidays to the user's Google Calendar
 */
export async function syncHolidaysToGoogleCalendar(userId: number) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    throw new AppError("Google account not linked.", 403);
  }

  const futureHolidays = await prisma.calendarException.findMany({
    where: {
      type: "HOLIDAY",
      date: { gte: startOfDay(new Date()) },
    },
    orderBy: { date: "asc" },
  });

  if (futureHolidays.length === 0) {
    return { syncedCount: 0, message: "No upcoming holidays to sync." };
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });
  let syncedCount = 0;

  // We loop through and insert. 
  // Optimization: We could search for existing events to avoid duplicates, but for simplicity we'll just insert.
  for (const holiday of futureHolidays) {
    try {
      await calendar.events.insert({
        calendarId: "primary",
        requestBody: {
          summary: `Holiday: ${holiday.name || "Public Holiday"}`,
          description: holiday.description || "Company Holiday from HRMS",
          start: { date: holiday.date.toISOString().split("T")[0] },
          end: { date: new Date(holiday.date.getTime() + 86400000).toISOString().split("T")[0] },
          transparency: "transparent", // free/available, just a reminder
          status: "confirmed",
        },
      });
      syncedCount++;
    } catch (err) {
      console.error(`Failed to sync holiday ${holiday.name}:`, err);
    }
  }

  return { syncedCount };
}

/**
 * Sends a notification to the configured Google Chat Webhook Space
 */
export async function sendTeamNotification(text: string) {
  const webhookUrl = process.env.GOOGLE_CHAT_WEBHOOK_URL;

  if (!webhookUrl) {
    console.warn("GOOGLE_CHAT_WEBHOOK_URL not configured. Skipping notification.");
    return { sent: false, reason: "Missing webhook URL" };
  }

  try {
    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=UTF-8" },
      body: JSON.stringify({ text }),
    });

    if (!response.ok) {
      throw new Error(`Google Chat Webhook failed: ${response.statusText}`);
    }

    return { sent: true };
  } catch (error) {
    console.error("Failed to send Google Chat notification:", error);
    return { sent: false, error };
  }
}
